language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: hjg4toezoHWwNob89cOdw0bBk83kdPjsQ8HZsf+K6fVLPQjWeni/SnyRupAhJn/KSCX04rwbGyVspITCSF+08wa0RMdor3Tb50B8YVgjmkzlpGbRfMLBCDgOU50BrkNH/uDk7lobYX7sUvgBwtzs16QmcIEA/vQ9dX6SRNNAKWnXq4f9OZJBs12gI8X/0nTGnI6rG5l4xIxEkOxnsKP/pxLMUp03GW7QYKQ9U6nUibaXaS3F/xDX9I216lwGXmfpBJ0Lj80sNYAM/25rtB7ZzW70MEkWwznKEKOsKCU+eFqN4ctJ2NFc/5UEXyOYcQgtk97EU3MN2n1JGroLkiXl9xTlhns8k6VjNq2XYil5cti0CAe5WiVx2ae2uKrBHDtimn5aZM2LIoygcMdDIOBLSCPqvOwDaRnDFr78FVZpgYjask3SPR+uDx12Qo/oaiBrVii3G8YzZzXkkszOUcQmhjT9wtwr/zlt0m11mGXMXK5oMBK81x1DHlVfoOJcGRuad1QQREzcq0NiI/ARKmEAspA1bI0hcKsIWvMWbmmzz6zbL3yGl72Eohg8/s1g/cZOErScFS4p/eiARhoxqM5nm3jPyQLZGQT/Y4oAWLg7Ls64wA4iwgQtfOKL2R6aN6onNDE6hmcBihjsxgzIf885lPObxxEe9Js2GIaC2k+E5KU=
