language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: BSFwJTNe91kD6wd9ezaTxMLCuSBsItn0Kfqrmc+iF8beQCw5+oxxqMfFZox30/G3OQQn/sFix2PpA8c08iiZ7GXNvqqnaC+3IftD1KzpX1YCujhzjqz+ocRi5nBDGX2dUStiz6Gs2Ix7Gf9n0MEWS7ODBZqUrd7LfLkDNJVWDixe1r5ZtQuOQc+23qZ2xqs0jBHvkRSTBLPVk3p7l86YVfFIQ18VY89iNi7U2DyXdpsSafkhvdm8N86MFxan2BJeDAh2Qkts2QPo0I0F2T1lOaFgJJVs3Asj7x7tVxhUMlnDlkC48dF3fUB+qh7NTPwD2jXpGHxj/d2LO/t7muzyWJjOtilpIz/kc3tbuqXO89ght87aGcu6v6JcIKQO/DPngcQBBTRN0mPkw3v/pdv5bBLq2GkT003a16Gcj2Dba2/XOIyKcoctMWCEX4nb1K4759wBPgzhr1lhYan9u7BiXACZqqiAuu+/WyU4Q+YzKsipm2f7Ktb1fRdwmP6KyL6VEwpDf7gYwGrWryIDgpx9RFUetCObvthL+ElaEOGDpM+lniRaDa4g9unqfBin06e1i9WB9RkzgIu9OEiOhXK7HAin0Cb0drf5bY/PDV8J7KwA9AFzGag47nNEUUl3Flsx/qChX83dm4hMhYnpVHi1U2OwjWhi/KBloci89IBdhgA=
  app: fof-app-api-users
  on:
    repo: ShinyVerse/fof-api
