language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: JDB7EUJKlAKR8dAoW4Alejh+MRg/+vL7pNJWRMI53lfRZs09lJ4y4xqtt9XHdXLHOtaD2lcHJVZAa5GosgZ3bZfZ+OOkARXiZUYn/5MXCy6V8NplEHutXIqOb1OWqFMerlDMYJHhy/pNaXDsUtf6lO9HPyMZ0N6GsR3ypkZupepdbkPFzopEGUEzpehBEhJ+IzH533BDEoGbmbbK9D241ezr1m2gwLeYvrwbZpAQtHRxvH8KlKvlKqPZk8cLWZmQ/97AiT47FHR9KXTk4QC+oe0QvriyRwym7R7V33SlT8Oteia1KMxUkbnOmVmDbR9bf5+QC4d8j85lcek0B75Y+9kFKhpUgW2duWk7Hy2fDqsQJtklSNwIGOA0snoN8mVPtl1Txjij2F0uQMGEEttUGAZwuNPc6qkA0BgkGcIPUWsNb0OmG5J5ixIw2hqPUzC9iqrws/6wJuJ9WfjlxamXN6+sS/Ks2AsgwTCVNBlc30QDw2XUjwTp0STjaLDk3HVqRJ9LuSpge1q1pAnETg8ZLjKMDQCKmXxKR5QcFcSuT3wH3GVRhmlx11K4EGQ/LLeTI/v9cJaQEYZYxYSr8hz7yGNMA+ATUZ36R8H8NDqLPK95yRUb4wimFB+S+u1Vwz6XL41fynqNTnXeqASxmB/5SBAj427kBLHu27tCphjuQ7Y=
    app: fof-app-api-users
