language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: iW/AjdQpNL0qejrN7FAdwzS2BdciDMkeNuUHG2B7u2JEsEs8AndAmdPDfRlaDfwje5XJKffxDrZVoGg5tLDc02Fgh0yZ87fAGIu3muTh3JhgYupk3kWC5mrL52esFL32CPZc+mSta0m8vJX7Es08wXyfEreOzohXIaZ8FuJdPeWUafcqci01F9cQUbOfhYOXkl1yYzt0ZVzhFr/4RkibCMSoDGGAurZ83BWVXrOk/u5uHV/CW2Ulu1hxPYVpDFsjEKmZKMAlu1uRQhkpyE2rzNsJLCLKaoH5KxXKYhmuQSXd+/qM4XnZBviotV4hzhRiEus2pzjNaqZkMCL1FyC+2z2atiG4JPO91/40Ebodvy1XUp4bCndp7cW7Fcs3kLLuoNsN+nVGrUmrBKWsD+YWfnfPa2r5GWezr5KmZckB29U1ti1nQrrITkjhj27QE+GbNYALXctWkJJ2DqE1lfCClH+1OA4iJBjs6ZXFaYGymJ6+bRpnwAUsWXU8giwY1DeDYbnA9BCyECb/9/cX7ldDIU+qLPKpk7GjeVtartnyFIxr8RSS84zIHiMmrFl7yxkTsfSe9zKNZbutTpNjpmjFqtl6QbmyBLpnebHI9YBlNKJ5xgLARxbtnqUbym0QU0eCp/JV2ZjNu2/Lb6Uy32Du0tjvU5E1hWyZgdo/fK6Vhyk=
